name: Create Network Visualization

on:
  push:
    paths:
      - 'data/graph_data.json'
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: write  # Needed to push to gh-pages branch
  pages: write     # Needed for GitHub Pages deployment
  id-token: write  # Needed for GitHub Pages deployment

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Create visualization
        run: |
          python scripts/create_viz.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

